//
// MDLDocument.h
//
// Copyright (c) 2012-2015 shazino (shazino SAS), http://www.shazino.com/
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.

@import Foundation;

extern NSString * const MDLDocumentTypeGeneric;
extern NSString * const MDLDocumentTypeJournal;

extern NSString * const MDLDocumentViewAll;
extern NSString * const MDLDocumentViewBIB;
extern NSString * const MDLDocumentViewClient;
extern NSString * const MDLDocumentViewTags;
extern NSString * const MDLDocumentViewPatent;

@class MDLGroup, MDLFile, MDLProfile;
@class MDLMendeleyAPIClient, MDLResponseInfo;
@class AFHTTPRequestOperation;

/**
 `MDLDocument` represents a user’s document, as described by Mendeley.
 */

@interface MDLDocument : NSObject

//*************************
// Core Document Attributes
//*************************

/**
 The document identifier, as generated by Mendeley.
 */
@property (copy, nonatomic) NSString *identifier;

/**
 The title of the document.
 */
@property (copy, nonatomic) NSString *title;

/**
 The type of the document. This is `@"generic"` by default.
 */
@property (copy, nonatomic) NSString *type;

/**
 The user that added the document to the system.
 */
@property (strong, nonatomic) MDLProfile *user;

/**
 The group of the document, if it belongs to one.
 */
@property (strong, nonatomic) MDLGroup *group;

/**
 The abstract of the document.
 */
@property (copy, nonatomic) NSString *abstract;

/**
 The publication outlet of the document.
 */
@property (strong, nonatomic) NSString *source;

/**
 The year of the document.
 */
@property (strong, nonatomic) NSNumber *year;

/**
 The authors of the document stored as MDLAuthor.
 */
@property (strong, nonatomic) NSArray *authors;

/**
 The document identifiers.
 */
@property (strong, nonatomic) NSDictionary *identifiers;

/**
 The keywords of the document.
 */
@property (strong, nonatomic) NSArray *keywords;


//***************************
// Catalog Document Attribute
//***************************

/**
 This is a catalog document.
 */
@property (nonatomic, assign) BOOL isCatalogDocument;


//*******************************
// Additional Document Attributes
//*******************************

///**
// The citation key of the document.
// */
//@property (copy, nonatomic) NSString *citationKey;
//

/**
 The Mendeley URL of the document.
 */
@property (strong, nonatomic) NSURL *mendeleyURL;

//
///**
// The URLs of the document, as a NSArray of NSURL objects.
// */
//@property (strong, nonatomic) NSArray *URLs;
//
///**
// The publisher of the document.
// */
//@property (copy, nonatomic) NSString *publisher;
//
///**
// The folder identifiers of the document.
// */
//@property (copy, nonatomic) NSArray *foldersIdentifiers;
//
///**
// The files of the document.
// */
//@property (strong, nonatomic) NSArray *files;
//

/**
 The read status of the document
 */
@property (strong, nonatomic) NSNumber *read;

/**
 The star status of the document
 */
@property (strong, nonatomic) NSNumber *starred;

//
///**
// The authored status of the document
// */
//@property (strong, nonatomic) NSNumber *authored;
//

/**
 The deletion pending status of the document
 */
@property (strong, nonatomic) NSNumber *inTrash;

//
///**
// The discipline of the document.
// */
//@property (copy, nonatomic) NSString *discipline;
//
///**
// The subdiscipline of the document.
// */
//@property (copy, nonatomic) NSString *subdiscipline;
//
///**
// The institution of the document.
// */
//@property (copy, nonatomic) NSString *institution;
//
///**
// The volume of the document.
// */
//@property (copy, nonatomic) NSString *volume;
//
///**
// The issue of the document.
// */
//@property (copy, nonatomic) NSString *issue;
//
///**
// The pages of the document.
// */
//@property (copy, nonatomic) NSString *pages;
//
///**
// The notes of the document.
// */
//@property (copy, nonatomic) NSString *notes;
//
///**
// The tags of the document.
// */
//@property (strong, nonatomic) NSArray *tags;
//
///**
// The cast of the document.
// */
//@property (strong, nonatomic) NSArray *cast;
//
///**
// The editors of the document.
// */
//@property (strong, nonatomic) NSArray *editors;
//
///**
// The producers of the document.
// */
//@property (strong, nonatomic) NSArray *producers;
//
///**
// The translators of the document.
// */
//@property (strong, nonatomic) NSArray *translators;
//
///**
// The added date of the document.
// */
//@property (strong, nonatomic) NSDate *addedDate;
//
///**
// The modified date of the document.
// */
//@property (strong, nonatomic) NSDate *modifiedDate;
//
///**
// The version of the document.
// */
//@property (strong, nonatomic) NSNumber *version;
//
///**
// The Open Access status of the document
// */
//@property (strong, nonatomic) NSNumber *openAccess;


/**
 Creates a `MDLDocument` and sends an API creation request using the shared client.
 
 @param document The document to create.
 @param success A block object to be executed when the request operation finishes successfully.
 This block has no return value and takes one argument: the created document with its newly assigned document identifier.
 @param failure A block object to be executed when the request operation finishes unsuccessfully, or that finishes successfully, but encountered an error while parsing the resonse data.
 This block has no return value and takes one argument: the `NSError` object describing the network or parsing error that occurred.
 
 @return  The newly-initialized document, with document identifier = `nil`.
 */
+ (instancetype)createDocument:(MDLDocument *)document
                    withClient:(MDLMendeleyAPIClient *)client
                       success:(void (^)(MDLDocument *))success
                       failure:(void (^)(NSError *))failure;

/**
 Sends a user library API request using the shared client.
 
 @param pageIndex The page index. `O` is first page.
 @param count The number of items returned per page.
 @param success A block object to be executed when the request operation finishes successfully.
 This block has no return value and takes five arguments: an array of `MDLDocument` objects, the total number of results, the total number of pages, the index of the current page, and the number of items per page.
 @param failure A block object to be executed when the request operation finishes unsuccessfully, or that finishes successfully, but encountered an error while parsing the resonse data.
 This block has no return value and takes one argument: the `NSError` object describing the network or parsing error that occurred.
 */
+ (void)fetchDocumentsInUserLibraryWithClient:(MDLMendeleyAPIClient *)client
                                         view:(NSString *)view
                                       atPage:(NSString *)pagePath
                                numberOfItems:(NSUInteger)numberOfItems
                                      success:(void (^)(MDLResponseInfo *info, NSArray *documents))success
                                      failure:(void (^)(NSError *))failure;

+ (void)fetchDocumentsInGroup:(MDLGroup *)group
                   withClient:(MDLMendeleyAPIClient *)client
                         view:(NSString *)view
                       atPage:(NSString *)pagePath
                numberOfItems:(NSUInteger)numberOfItems
                      success:(void (^)(MDLResponseInfo *info, NSArray *documents))success
                      failure:(void (^)(NSError *))failure;

/**
 Sends an API search request with generic terms using the shared client.
 
 @param terms The terms for the search query
 @param pageIndex The page index. `O` is first page.
 @param count The number of items returned per page.
 @param success A block object to be executed when the request operation finishes successfully. 
  This block has no return value and takes five arguments: an array of `MDLDocument` objects for the match, the total number of results, the total number of pages, the index of the current page, and the number of items per page.
 @param failure A block object to be executed when the request operation finishes unsuccessfully, or that finishes successfully, but encountered an error while parsing the resonse data. 
  This block has no return value and takes one argument: the `NSError` object describing the network or parsing error that occurred.
 */
+ (void)searchWithClient:(MDLMendeleyAPIClient *)client
                   terms:(NSString *)terms
                    view:(NSString *)view
                  atPage:(NSString *)pagePath
           numberOfItems:(NSUInteger)numberOfItems
                 success:(void (^)(MDLResponseInfo *info, NSArray *documents))success
                 failure:(void (^)(NSError *))failure;

/**
 Sends an API search request with specific terms using the shared client.
 
 @param genericTerms The terms for the search query
 @param authors The authors for the search query
 @param title The title for the search query
 @param year The year for the search query
 @param tags The tags for the search query
 @param pageIndex The page index. `O` is first page.
 @param count The number of items returned per page.
 @param success A block object to be executed when the request operation finishes successfully.
  This block has no return value and takes five arguments: an array of `MDLDocument` objects for the match, the total number of results, the total number of pages, the index of the current page, and the number of items per page.
 @param failure A block object to be executed when the request operation finishes unsuccessfully, or that finishes successfully, but encountered an error while parsing the resonse data. 
  This block has no return value and takes one argument: the `NSError` object describing the network or parsing error that occurred.
 */
+ (void)searchWithClient:(MDLMendeleyAPIClient *)client
                 authors:(NSString *)authors
                   title:(NSString *)title
                    year:(NSNumber *)year
                    view:(NSString *)view
                  atPage:(NSString *)pagePath
           numberOfItems:(NSUInteger)numberOfItems
                 success:(void (^)(MDLResponseInfo *info, NSArray *documents))success
                 failure:(void (^)(NSError *))failure;


/**
 Sends an API details request for the current document using the shared client.
 
 @param success A block object to be executed when the request operation finishes successfully.
 This block has no return value and takes one argument: the current document with its newly assigned details.
 @param failure A block object to be executed when the request operation finishes unsuccessfully, or that finishes successfully, but encountered an error while parsing the resonse data.
 This block has no return value and takes one argument: the `NSError` object describing the network or parsing error that occurred.
 */
- (void)fetchDetailsWithClient:(MDLMendeleyAPIClient *)client
                          view:(NSString *)view
                       success:(void (^)(MDLDocument *))success
                       failure:(void (^)(NSError *))failure;


/**
 Sends an API upload request using the shared client.
 
 Keep in mind that Mendeley only handles a limited number of file formats (.pdf, etc).
 
 @param fileURL The local URL for the file to upload.
 @param success A block object to be executed when the request operation finishes successfully. 
  This block has no return value and takes one argument: a `MDLFile` for the newly-uploaded file.
 @param failure A block object to be executed when the request operation finishes unsuccessfully, or that finishes successfully, but encountered an error while parsing the resonse data. 
  This block has no return value and takes one argument: the `NSError` object describing the network or parsing error that occurred.
 
 @return A new HTTP request operation
 */
- (AFHTTPRequestOperation *)uploadFileWithClient:(MDLMendeleyAPIClient *)client
                                           atURL:(NSURL *)fileURL
                                     contentType:(NSString *)contentType
                                        fileName:(NSString *)fileName
                                         success:(void (^)(MDLFile *newFile))success
                                         failure:(void (^)(NSError *))failure;

/**
 Sends an update document API request using the shared client.
 
 @param read The read status.
 @param success A block object to be executed when the request operation finishes successfully. 
  This block has no return value and takes one argument: a `MDLDocument` object.
 @param failure A block object to be executed when the request operation finishes unsuccessfully, or that finishes successfully, but encountered an error while parsing the resonse data. 
  This block has no return value and takes one argument: the `NSError` object describing the network or parsing error that occurred.
 */
- (void)markAsRead:(BOOL)read
        withClient:(MDLMendeleyAPIClient *)client
           success:(void (^)(MDLDocument *))success
           failure:(void (^)(NSError *))failure;

/**
 Sends an update document API request using the shared client.
 
 @param starred The starred status.
 @param success A block object to be executed when the request operation finishes successfully.
  This block has no return value and takes one argument: a `MDLDocument` object.
 @param failure A block object to be executed when the request operation finishes unsuccessfully, or that finishes successfully, but encountered an error while parsing the resonse data. 
  This block has no return value and takes one argument: the `NSError` object describing the network or parsing error that occurred.
 */
- (void)markAsStarred:(BOOL)starred
           withClient:(MDLMendeleyAPIClient *)client
              success:(void (^)(MDLDocument *))success
              failure:(void (^)(NSError *))failure;

/**
 Sends an update document API request using the shared client.
 
 @param success A block object to be executed when the request operation finishes successfully.
  This block has no return value and takes one argument: a `MDLDocument` object.
 @param failure A block object to be executed when the request operation finishes unsuccessfully, or that finishes successfully, but encountered an error while parsing the resonse data.
  This block has no return value and takes one argument: the `NSError` object describing the network or parsing error that occurred.
 */
- (void)updateDetailsWithClient:(MDLMendeleyAPIClient *)client
                        success:(void (^)(MDLDocument *))success
                        failure:(void (^)(NSError *))failure;

/**
 Sends an update document API request using the shared client.

 @param success A block object to be executed when the request operation finishes successfully. 
  This block has no return value and takes one argument: a `MDLDocument` object.
 @param failure A block object to be executed when the request operation finishes unsuccessfully, or that finishes successfully, but encountered an error while parsing the resonse data. 
  This block has no return value and takes one argument: the `NSError` object describing the network or parsing error that occurred.
 */
- (void)moveToTrashWithClient:(MDLMendeleyAPIClient *)client
                      success:(void (^)(MDLDocument *))success
                      failure:(void (^)(NSError *))failure;

/**
 Sends a delete document API request using the shared client.
 
 @param success A block object to be executed when the request operation finishes successfully. 
  This block has no return value and takes one argument: an array of `MDLDocument` objects.
 @param failure A block object to be executed when the request operation finishes unsuccessfully, or that finishes successfully, but encountered an error while parsing the resonse data. 
  This block has no return value and takes one argument: the `NSError` object describing the network or parsing error that occurred.
 */
- (void)deleteWithClient:(MDLMendeleyAPIClient *)client
                 success:(void (^)())success
                 failure:(void (^)(NSError *))failure;

@end
